name: currency_converter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  dio: ^4.0.6
  http: ^0.13.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

 